baseURL = 'https://yixinyi.github.io/BasedKeto/'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false  # Changed to false
theme = "ananke"

[languages.en]
languageName = "English"
weight = 1
title = "BasedKeto"

[languages.zh]
languageName = "中文"
weight = 2
title = "根基生酮"

[params]
mainSections = ["posts"]
displayFullLangName = true

[languages.en.params]
mainSections = ["posts"]

[languages.zh.params]
mainSections = ["posts"]

[menu]

  [[languages.en.menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 10

  [[languages.zh.menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 10
